Repository wecode-bootcamp-korea/26-2nd-Holla-frontend, pull requests merged in 2021-11, with the labels that each got.

#5 [26기 설혜린] 카카오톡 로그인창 이동
  package-lock.json
  package.json
  public/data/SlideData.json
  public/data/data.md
  public/index.html
  src/Routes.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/NavMenu/NavMenu.js
  src/components/NavMenu/NavMenu.scss
  src/config.js
  src/styles/common.scss
Labels: Status: Accepted

#1 [26기 정지후] Add: Main - 메인 배너 슬라이드 레이아웃 구현중
  package-lock.json
  package.json
  public/data/mainSlideData.json
  public/index.html
  src/Routes.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Main/BannerSlide/BannerSlide.js
  src/pages/Main/BannerSlide/BannerSlide.scss
  src/pages/Main/BannerSlide/bannerSlideDate.js
  src/pages/Main/CommonSlide/CommonSlide.js
  src/pages/Main/CommonSlide/CommonSlide.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: Accepted

#3 [26기 이수경] Modified: Modal 외부 영역 클릭 시 Modal 창 꺼지는 기능 구현
  package-lock.json
  public/data/Detail.json
  public/data/Review.json
  src/components/Nav/Nav.js
  src/pages/DetailPage/DetailComment/DetailComment.js
  src/pages/DetailPage/DetailComment/DetailComment.scss
  src/pages/DetailPage/DetailIntro/DetailIntro.js
  src/pages/DetailPage/DetailIntro/DetailIntro.scss
  src/pages/DetailPage/DetailNewModal/DetailNewModal.js
  src/pages/DetailPage/DetailNewModal/DetailNewModal.scss
  src/pages/DetailPage/DetailPage.js
  src/pages/DetailPage/DetailPage.scss
  src/pages/DetailPage/DetailReviewStar/DetailReviewStar.js
  src/pages/DetailPage/DetailReviewStar/DetailReviewStar.scss
  src/pages/DetailPage/ViewMore/ViewMore.js
  src/pages/DetailPage/ViewMore/ViewMore.scss
  src/pages/Main/Main.js
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#4 [26기 장세영] 장바구니 레이아웃 구현 및 컴포넌트 분리
  public/data/cartData 2.json
  public/data/cartData 3.json
  public/data/cartData.json
  public/images/sample 2.png
  public/images/sample 3.png
  public/images/sample.png
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartCheck/CartCheck.js
  src/pages/Cart/CartCheck/CartCheck.scss
  src/pages/Cart/CartList/CartList.js
  src/pages/Cart/CartList/CartList.scss
  src/pages/Cart/CartPayment/CartPayment.js
  src/pages/Cart/CartPayment/CartPayment.scss
  src/pages/Cart/CartTotal/CartTotal.js
  src/pages/Cart/CartTotal/CartTotal.scss
Labels: Status: 수정 요청
